docs: add more description for delete command
labring/sealos pull request #1135
Opened 2022-06-18 13:33 UTC by gitccl

[SKIP CI]seaols: solve #1068 
Closes #1068

2022-06-18 13:38 UTC, cuisongliu approved these changes

2022-06-18 13:42 UTC, cuisongliu requested changes

2022-06-18 13:42 UTC, cuisongliu commented on cmd/sealos/cmd/delete.go
>  delete to default cluster:
this tips can remove it, delete cmd can't delete cluster .add tips delete to masters

2022-06-19 00:48 UTC, fanux commented on cmd/sealos/cmd/delete.go
> +delete to masters:
delete to masters -> delete masters

2022-06-19 00:50 UTC, fanux commented on cmd/sealos/cmd/delete.go
> +Please note:
Please note that sealos will delete your master if the --masters parameter is specified.

2022-06-19 02:07 UTC, cuisongliu approved these changes

2022-06-19 02:07 UTC, merged