build pgsql & add pgsql service api
labring/sealos pull request #2256
Opened 2022-12-13 07:10 UTC by zjy365

Signed-off-by: zhu jing yang <3161362058@qq.com>

2022-12-16 04:15 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/add_page.tsx
> +    const res = await request.post('/api/pgsql/applyPgsql', { data, kubeconfig });
如果接口请求失败了，也会跳转么？

2022-12-16 04:16 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/add_page.module.scss
> +.copyBtn {
button 相关的样式 , card 相关的样式 需要单独抽离出来，放到单独组件。

2022-12-16 04:35 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/front_page.tsx
> +      enabled: pgsqlListStatus === 'Pending' // 只有 url 为 '' 的时候需要请求
这里的 pgsqlListStatus  应该改成枚举值

2022-12-16 04:37 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/front_page.tsx
> +      item?.status?.PostgresClusterStatus ? item?.status?.PostgresClusterStatus : 'emptyStatus'
这里的状态值「 emptyStatus 」 也是一样

2022-12-16 04:42 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/front_page.tsx
> +                          styles[item.status?.PostgresClusterStatus || 'emptyStatus'],
直接用后端返回的数据作为 styles 的 key 不是很好，如果后端的数据 从 'emptyStatus' 改成了 'EmptyStatus' ，那这里的代码是感知不到的。这里的样式由  styles['emptyStatus'] 就会变成 styles['EmptyStatus'] ，但这个样式是没有的，就会出错。

2022-12-16 06:32 UTC, zjy365 commented on desktop/frontend/src/applications/pgsql/add_page.tsx
> +    const res = await request.post('/api/pgsql/applyPgsql', { data, kubeconfig });
是的

2022-12-16 06:56 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/index.tsx
> +  const text = `\`\`\`yaml
这种 defaultText 最好单独一个文件，不然会显著增加文件的行数。影响正常逻辑代码的阅读。

2022-12-16 06:57 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/pgsql.common.scss
> +.Running {
因为需要跟后端字段一致，所以导致这边的 css 命名规则也会不符合标准。

2022-12-16 07:43 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/components/fluent_rhf.tsx
> +import { FC } from 'react';
文件名有问题， fluent_rhf 不知道什么意思。

2022-12-16 07:45 UTC, LeezQ reviewed
reviewed

2022-12-16 10:59 UTC, zjy365 commented
![image](https://user-images.githubusercontent.com/72259332/208083919-5cd35c52-102c-4fa2-8d6e-cf9e06531b4a.png)
![image](https://user-images.githubusercontent.com/72259332/208083952-de791b12-5741-4283-b468-7c40dcc1d81c.png)

2022-12-17 02:40 UTC, zjy365 commented
![image](https://user-images.githubusercontent.com/72259332/208219839-f5c18399-c58c-4617-b909-999787c5236c.png)

2022-12-19 07:44 UTC, LeezQ requested changes
这么多 svg 的图片，如果是跟 icon 相关的，让 UI 统一放到  iconfont.cn 去维护。

2022-12-19 07:44 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/front_page.tsx
> +import { EPgsqlLists, EPgsqlStatus, TPgsqlDetail } from './pgsql.common';
没有 pgsql.common 这种命名规范，直接 pgsql_common 就好了

2022-12-19 07:44 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/components/button.tsx
> +          [styles.mini]: size === 'mini'
这里写法很多余啊，type 是你自己传进来的。直接  styles[type] , styles[size] 就好了。

2022-12-19 07:44 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/components/button.tsx
> +        plain && styles.plain
这三个应该是一个属性的，大小： size， 颜色/按扭分类： type， 形状：shape， round、squareRound 这几个应该属于形状

2022-12-19 07:44 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/components/button.tsx
> +        plain && styles.plain
plain 是什么效果？

2022-12-19 07:44 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/components/button.tsx
> +          [styles.lightBlue]: type === 'lightBlue'
这里 type 颜色 和功能混用啊，这个属性不够清晰， delete 属于功能操作了，要么就是 error，应该用颜色来区分按扭场景的

2022-12-19 07:44 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/clusterInfo.module.scss
> +@import './pgsql.common.scss';
不需要 .common.css 这样的命名，直接 pgsql_common 就好了。

2022-12-19 07:44 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/clusterInfo.module.scss
> +  color: #273b58;
这些颜色是 UI  随便设的吗？ 这种色值需要跟 UI 提取出来。

2022-12-19 07:44 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/front_page.tsx
> +                      </div>
这段出现多次了，可以抽取成组件。

2022-12-19 07:44 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/front_page.tsx
> +                        icon={'/images/pgsql/delete.svg'}
这些 icon 的 svg 让 UI 统一放到 iconfont.cn 或者相关的 icon 库去维护。

2022-12-19 09:45 UTC, zjy365 commented on desktop/frontend/src/applications/pgsql/components/button.tsx
> +        plain && styles.plain
![Uploading image.png…]()

2022-12-19 09:45 UTC, zjy365 commented on desktop/frontend/src/applications/pgsql/components/button.tsx
> +        plain && styles.plain
![image](https://user-images.githubusercontent.com/72259332/208396411-77dfc813-d047-4f12-9244-2caac6fcbc82.png)

2022-12-21 06:23 UTC, zjy365 commented
icon问题  ui 还没准备好，准备好了再修改

2022-12-21 08:06 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/components/button.tsx
> +  squareRound?: boolean;
这两个没用到

2022-12-21 08:08 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/components/delete_dialog.tsx
> +  open: boolean;
open -> isOpen

2022-12-21 08:08 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/components/delete_dialog.tsx
> +  onChangeOpen: (open: boolean) => void;
onChangeOpen -> onOpen

2022-12-21 08:52 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/components/delete_dialog.tsx
> +    while (!fresh && deleteComplete) {
这段需要重构下,现在的实现不是很好.

2022-12-21 09:17 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/clusterInfo.tsx
> +              secretResult?.body?.data?.username && window.atob(secretResult?.body?.data?.username),
上面已经判断过了,这里有点重复.

2022-12-21 09:23 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/front_page.tsx
> +  const curApp = openedApps.find((item) => item.name === currentApp?.name);
这个 curApp 和 currentApp 有什么不同?

2022-12-21 09:25 UTC, zzjin commented on desktop/frontend/src/pages/api/pgsql/deletePgsql.ts
> +  };
This meta should also move to mock dir too. 
Without hard code.

2022-12-21 09:25 UTC, zzjin commented on desktop/frontend/src/pages/api/pgsql/getAll.ts
> +  const meta: CRDMeta = {
Same as above

2022-12-21 09:26 UTC, zzjin commented on desktop/frontend/src/pages/api/pgsql/getAll.ts
> +  if (kube_user === null) {
We have common resp status at file:  `src/pages/api/response.ts` to return frontend same error message struture.

2022-12-21 09:57 UTC, zjy365 commented on desktop/frontend/src/applications/pgsql/front_page.tsx
> +  const curApp = openedApps.find((item) => item.name === currentApp?.name);
好像不需要curApp，我删除一下

2022-12-21 10:02 UTC, zjy365 commented on desktop/frontend/src/applications/pgsql/front_page.tsx
> +  const curApp = openedApps.find((item) => item.name === currentApp?.name);
不行，这个currentApp ,不会变； currentApp.size  始终都是maximize
openedApps 里面的是会变的

2022-12-21 12:51 UTC, zzjin approved these changes

2022-12-21 15:12 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/clusterInfo.tsx
> +    const result: any = [];
any -> TInfoData[]

2022-12-21 15:15 UTC, LeezQ commented on desktop/frontend/src/applications/pgsql/front_page.tsx
> +  const curApp = openedApps.find((item) => item.name === currentApp?.name);
那 openedApps 变的时候,currentApp 应该也一起变吧

2022-12-22 02:11 UTC, zjy365 commented on desktop/frontend/src/applications/pgsql/clusterInfo.tsx
> +    const result: any = [];
![image](https://user-images.githubusercontent.com/72259332/209039858-20ce64cf-cb34-49b4-adce-53789f075a7b.png)

2022-12-22 07:59 UTC, LeezQ approved these changes

2022-12-22 08:01 UTC, merged