feature(main): fix registry find manifest logic
labring/sealos pull request #2314
Opened 2022-12-28 10:15 UTC by cuisongliu

Signed-off-by: cuisongliu <cuisongliu@qq.com>

2022-12-31 13:36 UTC, fanux commented on pkg/registry/cmd/flags.go
> +		os.Exit(1)
return error instead exit

2022-12-31 13:44 UTC, fanux commented on pkg/registry/cmd/save.go
> +				os.Exit(1)
RunE and return error

2022-12-31 13:46 UTC, fanux commented on pkg/registry/filter.go
> +	check := func(filter string, t FilterType) (FilterStrategy, error) {
Why not just use regular expressions

2022-12-31 13:47 UTC, fanux commented on pkg/registry/list.go
> +		repos, _ = reg.Repositories(func(data []string) []string {
ignore errors?

2023-01-01 05:21 UTC, SignorMercurio requested changes

2023-01-01 05:21 UTC, SignorMercurio commented on docs/4.0/docs/examples/sealctl-registry.md
> +# Using sealctl manager registry image
```suggestion
# Using sealctl to manage registry images
```

2023-01-01 05:21 UTC, SignorMercurio commented on docs/4.0/docs/examples/sealctl-registry.md
> +## Image save to local registry dir
```suggestion
## Save images to local registry directory
```

2023-01-01 05:21 UTC, SignorMercurio commented on docs/4.0/docs/examples/sealctl-registry.md
> +#### How to using
Please replace `How to using` with `Usage` globally.

```suggestion
#### Usage
```

2023-01-01 05:21 UTC, SignorMercurio commented on docs/4.0/docs/examples/sealctl-registry.md
> +default type can auto list images, using rootfs list images logic .ex charts,manifests,images dir.
Not sure how to change this right now. Any clarification?

2023-01-01 05:21 UTC, SignorMercurio commented on docs/4.0/docs/examples/sealctl-registry.md
> +## Status registry
```suggestion
## Check registry status
```

2023-01-01 05:21 UTC, SignorMercurio commented on docs/4.0/docs/examples/sealctl-registry.md
> +need sealctl login or sealos login it.
```suggestion
To use this command, you need to `sealctl login` or `sealos login` first.
```

2023-01-01 05:21 UTC, SignorMercurio commented on docs/4.0/docs/examples/sealctl-registry.md
> +root@default-golang-0:~# sealctl  registry  status
I think things like `root@default-golang-0:~#` does not provide useful information and should be replaced with a cleaner `$` just to show that we're in the command line. We should not simply copy from our terminal and paste it into the docs without any modification.

```suggestion
$ sealctl registry status
```

2023-01-01 05:21 UTC, SignorMercurio commented on docs/4.0/docs/examples/sealctl-registry.md
> +```
```suggestion
```shell
```

2023-01-01 05:21 UTC, SignorMercurio commented on docs/4.0/docs/examples/sealctl-registry.md
> +  `*val*`: contains
```suggestion
### Filtering

Keys for `--filter`:
- `name`
- `tag`

Expressions:
- `*val`: suffix 
- `val*`: prefix
- `value`: equals
- `<none>`: empty
- `*val*`: contains
```

2023-01-01 05:21 UTC, SignorMercurio commented on docs/4.0/docs/examples/sealctl-registry.md
> +sealctl  registry  rmi 192.168.64.63:5000/kube-apiserver:v1.19.0 -n 192.168.64.63:5000
We should either use:

<pre>
```shell
$ sealctl <commands> ...
```
</pre>

Or:

<pre>
```shell
sealctl <commands> ...
```
</pre>

And should not use them both.

2023-01-01 05:21 UTC, SignorMercurio commented on docs/4.0/docs/examples/sealctl-registry.md
> +Must be using in registry node, using binary deploy mode.Not support container deploy.
```suggestion
This command can only be run on a registry node, which used the binary deploy mode. Does not support nodes using container deploy mode.
```

2023-01-03 15:13 UTC, fanux approved these changes

2023-01-03 15:14 UTC, merged