init image hub page & image hub api
labring/sealos pull request #2321
Opened 2022-12-30 02:31 UTC by zjy365

2023-01-03 02:57 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/components/button.tsx
> +      {icon && <Image src={icon} alt="pgsql" width={16} height={16} />}
Image icon maybe undefined

2023-01-03 03:00 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/components/labels.tsx
> +      return <div></div>;
just return null ?

2023-01-03 03:02 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/app_store_common.ts
> +export const imagehubLabels = [
const variables should be Camel_Case

2023-01-03 03:03 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/app_store_common.ts
> +export const imagehubLabels = [
no type defined

2023-01-03 03:04 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/app_store_common.ts
> +  if (imageName) {
imageName 已经是不可选类型了,所以不可能为空,这里的判断多余, 要么就把imageName 改成可选, imageName?: string

2023-01-03 03:05 UTC, zjy365 commented
![image](https://user-images.githubusercontent.com/72259332/210295279-1340471a-a94c-4c40-9696-42efc749b966.png)

2023-01-03 03:05 UTC, zjy365 commented
![image](https://user-images.githubusercontent.com/72259332/210295308-215de24e-2ae3-4e25-99d2-1e07bbc631db.png)

2023-01-03 03:05 UTC, zjy365 commented
![image](https://user-images.githubusercontent.com/72259332/210295328-978c0b0b-e2fa-44b6-a8e2-1f5645a79f38.png)

2023-01-03 03:06 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/detail.module.scss
> +      &Text {
这个 &Text 是 .appDescText  ?

2023-01-03 03:10 UTC, zjy365 commented
![image](https://user-images.githubusercontent.com/72259332/210295579-da3a6739-1069-4778-9c0b-f716fff441a4.png)

2023-01-03 03:19 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/store_page.tsx
> +          const notCheckAll = draft.every((item) => item.checked === true);
变量命名不对吧,反了, 这里的返回的结果应该是是否已全部选择, isCheckAll

2023-01-03 03:24 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/store_page.tsx
> +    }
没有 else 导致下面的逻辑会一直运行. 不管 value 是 'All' 还是别的.

2023-01-03 03:29 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/store_page.tsx
> +      })
这整段逻辑看着有点乱。

2023-01-03 03:33 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/store_page.tsx
> +    }
这里为什么要遍历两次呢。
直接 imageLabels.map((item) => {
 // 在这里处理逻辑就好了。
})

2023-01-03 03:34 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/store_page.tsx
> +    let temp = imageLabels.filter((item) => item.checked === true).slice(1);
.slice(1); 这种逻辑太坑了。就是为了过滤掉 「All」么，那如果 「All」不在第一项了呢。

2023-01-03 03:36 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/store_page.tsx
> +                        <div className="w-20 h-20  pt-6  pr-6">
"w-20 h-20 pt-6 pr-6"  中间有多余空格

2023-01-03 03:46 UTC, LeezQ commented on desktop/frontend/next.config.js
> +const isProduction = process.env.NODE_ENV === 'production'
改过 prettier 配置了？ 怎么 「;」 都没了。

2023-01-03 03:48 UTC, zjy365 commented
没有改过prettier
&nbsp;


朱静洋
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月3日(星期二) 中午11:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [labring/sealos] init image hub page &amp; image hub api  (PR #2321)





 
@LeezQ commented on this pull request.
 
 
In desktop/frontend/next.config.js:
 &gt; @@ -1,12 +1,12 @@  // @ts-check -const runtimeCaching = require('next-pwa/cache'); -const isProduction = process.env.NODE_ENV === 'production'; +const runtimeCaching = require('next-pwa/cache') +const isProduction = process.env.NODE_ENV === 'production'  
改过 prettier 配置了？ 怎么 「;」 都没了。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-01-03 03:50 UTC, LeezQ commented on desktop/frontend/src/applications/infra/infra_share.ts
> +function conversionPrice(price: number, reserve: number) {
reserve 加个默认值 2

2023-01-03 03:51 UTC, LeezQ commented on desktop/frontend/src/pages/api/image_hub/get_detail.ts
>      if (dataDesc !== null && dataDesc.body !== null && dataDesc.body.status !== null) {
if (dataDesc?.body?.status) 就可以了

2023-01-03 03:52 UTC, LeezQ commented on desktop/frontend/src/pages/api/image_hub/get_detail.ts
> +          result.push(datapackDesc.datas[key]);
const resutl result = Object.values(datapackDesc.datas) 就可以了。

2023-01-03 03:53 UTC, LeezQ commented on desktop/frontend/src/pages/api/image_hub/get_detail.ts
> +          result.push(datapackDesc.datas[key]);
看下别的地方是不是也有同样的写法，一起改掉好了。

2023-01-03 03:53 UTC, zjy365 commented on desktop/frontend/src/pages/api/image_hub/get_detail.ts
> +          result.push(datapackDesc.datas[key]);
ok

2023-01-03 03:54 UTC, zjy365 commented on desktop/frontend/next.config.js
> +const isProduction = process.env.NODE_ENV === 'production'
没改过prettier

2023-01-03 05:43 UTC, zjy365 commented on desktop/frontend/src/applications/app_store/components/button.tsx
> +      {icon && <Image src={icon} alt="pgsql" width={16} height={16} />}
![image](https://user-images.githubusercontent.com/72259332/210305255-a4cdcabb-eac9-43d8-83bb-c2c1aa8dfe23.png)
我遇到了这个按钮，所以当icon不存在就不渲染Image的icon

2023-01-03 12:17 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/components/labels.tsx
> +    const isCheckedLabels = labels.filter((item) => item.checked === true);
isCheckedLabels  -> checkedLabels

2023-01-03 12:18 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/components/labels.tsx
> +    }
setAllActive(isCheckedLabels.length > 0)

2023-01-03 12:21 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/components/labels.tsx
> +          }
draft.forEach((item) => (item.checked = !isCheckAll));

2023-01-03 12:22 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/store_page.module.scss
> +    border: 0.5px solid $des-text-color;
border 0.5 ?

2023-01-03 12:28 UTC, LeezQ commented on desktop/frontend/src/pages/api/image_hub/get_detail.ts
> +      if (datapackDesc.codes === 1) {
「1」 需要提取成常量。

2023-01-03 12:29 UTC, LeezQ commented on desktop/frontend/src/pages/api/image_hub/get_list.ts
> +    if (repositoryDesc !== null && repositoryDesc.body !== null) {
这里没改 ，直接 if (repositoryDesc?.body)

2023-01-03 12:30 UTC, LeezQ commented on desktop/frontend/src/pages/api/image_hub/get_list.ts
> +      if (datapackDesc.codes === 1) {
「1」 提取常量

2023-01-05 03:17 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/components/labels.tsx
> +  }, [labels]);
这个 useEffect 是没必要的。

const [selectedLabels, setSelectedLabels] = useState<TImageLabels[]>(props.lables || []); 
这里应该给初始值。 
allActive 也是不需要的，可以直接通过 props.lables 算出来的，不需要依赖 labels 的变化。

2023-01-05 03:53 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/components/labels.tsx
> +  }, [labels]);
原文：https://beta.reactjs.org/learn/you-might-not-need-an-effect
翻译：https://juejin.cn/post/7123928175985295367

2023-01-05 03:53 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/components/labels.tsx
> +          onClick={() => handleClick('All')}
'All' 需要提取出来。如果做国际化的话，这里的 All ，中文里应该叫「全部」，到时候怎么处理？

2023-01-05 03:53 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/store_page.tsx
> +      refetchInterval: appListStatus === false ? 2 * 1000 : false,
appListStatus 本身就是 bool 值， === false 多此一举啊。

2023-01-05 03:53 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/store_page.tsx
> +      if (item.checked === true) {
这种地方也是。

2023-01-05 03:53 UTC, LeezQ commented on desktop/frontend/src/components/iconfont/index.tsx
> +      <Script src="//at.alicdn.com/t/c/font_3832498_su260k21s5.js" async></Script>
每次 render 这个 Iconfont 的时候，都加载一行   <Script src="//at.alicdn.com/t/c/font_3832498_su260k21s5.js" async></Script>  ？？？？！！！

2023-01-05 03:53 UTC, LeezQ commented on desktop/frontend/src/styles/globals.scss
>    --page-bg: rgb(255 255 255 / 3.33%);
有这个 dark mode 吗？ 没有的话，把一些没用的 css 清理下。

2023-01-05 03:58 UTC, zjy365 commented on desktop/frontend/src/styles/globals.scss
>    --page-bg: rgb(255 255 255 / 3.33%);
ok

2023-01-05 04:01 UTC, zjy365 commented on desktop/frontend/src/components/iconfont/index.tsx
> +      <Script src="//at.alicdn.com/t/c/font_3832498_su260k21s5.js" async></Script>
这个我测着，只会加载一行；
我要把它换到 _document 这里吗

2023-01-05 04:18 UTC, zjy365 commented on desktop/frontend/src/applications/app_store/components/labels.tsx
> +  }, [labels]);
good

2023-01-06 04:04 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/app_store_common.ts
> +export function formattedSize(size: number, reserve: number = 1) {
这里的第二个参数类型直接用  'B' | 'KB' | 'MB' 这样的吧，数字在使用的时候不够清晰。

2023-01-06 04:07 UTC, zjy365 commented on desktop/frontend/src/applications/app_store/app_store_common.ts
> +export function formattedSize(size: number, reserve: number = 1) {
这个单位是根据计算转换出来的，第二个参数为了前面数字保留的位数

2023-01-06 06:30 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/app_store_common.ts
> +    .filter((item) => item)
这个 filter 什么用？

2023-01-06 06:32 UTC, zjy365 commented on desktop/frontend/src/applications/app_store/app_store_common.ts
> +    .filter((item) => item)
map 返回的数组有null值

2023-01-06 06:33 UTC, zjy365 commented on desktop/frontend/src/applications/app_store/app_store_common.ts
> +    .filter((item) => item)
如何null 替换为 ‘’ 是否可以解决这个问题

2023-01-06 07:19 UTC, LeezQ requested changes

2023-01-06 07:19 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/components/labels.tsx
> +    );
这个方法应该叫 onChange，处理完后把值返回给组件外面。 现在的代码，一段逻辑在组件里，一段又在外面，无法知道 draft 是什么东西，

2023-01-06 07:19 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/components/labels.tsx
> +  const selectedLabels = labels.filter((item) => item.checked);
这里的 labels ，不需要 selectedLabels ，处理好，让组件传进来。

2023-01-06 07:19 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/store_page.tsx
> +          <Labels display="row" labels={imageLabels} setLabelsFunction={setImageLabels} />
这里的 labels，应该处理后 
<Labels display="row" labels={imageLabels.filter(item => item.checked)} onChange={(value) => {
....
} />

2023-01-06 07:19 UTC, LeezQ commented on desktop/frontend/src/pages/_app.tsx
> +
多了空行。

2023-01-06 07:19 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/detail_page.tsx
> +      refetchInterval: appDetailStatus === false ? 2 * 1000 : false,
bool 值都不需要 appDetailStatus === false，直接 !appDetailStatus 就行

2023-01-06 07:19 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/detail_page.tsx
> +          {isFixed ? (
在最外层加 styles.fixed ，然后通过 css 去控制样式。不需要到处 isFixed 判断。

2023-01-07 11:33 UTC, LeezQ approved these changes

2023-01-07 11:34 UTC, merged