enable cloud provider to scale cluster
labring/sealos pull request #2387
Opened 2023-01-12 06:41 UTC by xiaohan1202

2023-01-12 13:13 UTC, zzjin commented on controllers/cluster/controllers/cluster_controller.go
> +	"github.com/labring/sealos/pkg/utils/logger"
Controllers can direct use kubebuilder‘s reconcile logger to log informations, there is no such need to use sealos's `pkg/logger`, witch will cause package all `sealos/pkg` code, seems too large for controller.

2023-01-12 13:14 UTC, zzjin requested changes
Need remove requirements.

2023-01-13 03:08 UTC, fanux approved these changes

2023-01-13 04:44 UTC, zzjin commented on controllers/cluster/controllers/cluster_controller.go
> +	"github.com/go-logr/logr"
<img width="678" alt="image" src="https://user-images.githubusercontent.com/679757/212239320-6e4d650f-b312-497a-bc51-09b4425a4854.png">
Use buildin log like user controller.

2023-01-13 04:44 UTC, zzjin commented on go.work
> +replace k8s.io/mount-utils => k8s.io/mount-utils v0.24.3
These changes can also be removed?

2023-01-13 07:01 UTC, zzjin commented on controllers/cluster/controllers/cluster_controller.go
> +		User:   "root",
Remove hardcoded `root` with `infra.Spec.SSH.User` or `defaultUser`?

2023-01-16 01:19 UTC, zzjin approved these changes

2023-01-16 14:05 UTC, merged