docs: add account docs
labring/sealos pull request #2434
Opened 2023-01-18 08:59 UTC by xiao-jay

Signed-off-by: 晓杰 <2561589453@qq.com>

中文版ok写英文版

- [ ] english docs

2023-01-18 09:18 UTC, zzjin commented
支付的二维码,打个码或者替换成没有实际作用的二维码 文档里面直接可以扫的二维码不太安全

2023-01-18 11:08 UTC, xiao-jay commented
> 支付的二维码,打个码或者替换成没有实际作用的二维码 文档里面直接可以扫的二维码不太安全

现在扫显示已过期

2023-01-18 13:51 UTC, zzjin commented
Need EN version

2023-01-18 13:52 UTC, zzjin requested changes
Move cn doc to docs/4.0/i18n/zh-Hans/cloud/apps and put en version file here.

2023-01-19 04:44 UTC, xiao-jay commented
> Move cn doc to docs/4.0/i18n/zh-Hans/cloud/apps and put en version file here.

done

2023-01-19 05:29 UTC, fanux commented
这个现在放有点敏感，可以以后线上集群再合并我觉得

2023-01-19 05:29 UTC, closed without merging