image hub list paging & pagination component
labring/sealos pull request #2437
Opened 2023-01-18 09:48 UTC by zjy365

Signed-off-by: zhu jing yang <3161362058@qq.com>

1. image hub list paging
2. sealos cloud provider detail version
3. change sealos document link

2023-01-18 09:59 UTC, LeezQ requested changes

2023-01-18 09:59 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/app_store_common.ts
>  export function sortByName(arr: TAppInfo[]) {
这个方法是做了去重，然后做了一次按 name 排序么？写的有点复杂，可以优化下

2023-01-18 09:59 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/components/pgination.tsx
> + * 其余情况则头尾都渲染省略...项,第1页及总分页数,中间渲染页码。
代码中使用英文

2023-01-18 09:59 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/components/pgination.tsx
> +      key={'first' + Math.random()}
不要用 Math.random() 做 key

2023-01-18 09:59 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/detail_page.tsx
> +    appRef.current?.addEventListener('scroll', handleScrollEvent);
scroll 事件最好加 debounce

2023-01-18 13:30 UTC, LeezQ requested changes

2023-01-18 13:30 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/app_store_common.ts
> +    var val1 = a.name;
var ???

2023-01-18 13:30 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/app_store_common.ts
> +    var val1 = a.name;
复制过来的代码最好自己看下。

2023-01-18 13:30 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/components/pgination.tsx
> +        lastPage
这一坨写的是啥啊。

2023-01-18 13:31 UTC, LeezQ commented
好好重构下吧。

2023-01-19 06:22 UTC, LeezQ requested changes

2023-01-19 06:22 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/app_store_common.ts
> +  });
再优化

2023-01-19 06:22 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/app_store_common.ts
> +  };
直接用 lodash 的好了

2023-01-19 06:22 UTC, LeezQ commented on desktop/frontend/src/applications/app_store/components/pgination.tsx
> +  const initSecialPage = () => {
initSecialPage ?   ->  initSpecialPage ?

2023-01-19 06:35 UTC, zjy365 commented on desktop/frontend/src/applications/app_store/app_store_common.ts
> +  };
那要去引入吗

2023-01-19 06:37 UTC, zjy365 commented on desktop/frontend/src/applications/app_store/components/pgination.tsx
> +  const initSecialPage = () => {
实际应用，由于api原因，不能向后跳页，所以写了个特例

2023-01-19 09:07 UTC, LeezQ approved these changes

2023-01-19 09:08 UTC, merged