fix(auth): replace user id with nanoId
labring/sealos pull request #2443
Opened 2023-01-20 11:49 UTC by Abingcbc

2023-01-20 12:14 UTC, zzjin commented on pkg/auth/utils/config.go
> +	if len(users.Items) == 0 {
Should we check len(users.Items) must be 1?

2023-02-06 07:07 UTC, cuisongliu commented on pkg/auth/utils/config.go
> +			user.Object["metadata"].(map[string]interface{})["labels"].(map[string]interface{})["updateTime"] = time.Now().Format("T2006-01-02T15-04-05")
The writing is a bit complicated
```
labels:=user.GetLabels()[updateTime]=xxx
user.SetLabels(label)
```

2023-02-16 14:49 UTC, zzjin requested changes
Need to add old users sync script.

2023-02-18 07:50 UTC, fanux commented
@zzjin I accept to clean up the old users directly, the migration cost is too high, and such things will not happen in the future

2023-02-20 03:33 UTC, zzjin approved these changes

2023-02-20 03:34 UTC, zzjin approved these changes

2023-02-20 03:34 UTC, merged