remove duplicate pull image
labring/sealos pull request #2492
Opened 2023-02-02 14:56 UTC by huiwq1990

Signed-off-by: huiwq1990 <huiwq1990@163.com>

Fix duplicate scene.

```
2023-02-02T01:07:45 debug search images  platform: linux,amd64, , dir: /root/cloud-images/hello/registry, image list: [docker.io/library/nginx:1.23.1 nginx:1.23.1]
Pulling image: docker.io/library/nginx:1.23.1
Pulling image: docker.io/library/nginx:1.23.1
```

2023-02-02 15:05 UTC, zzjin commented
Good First Contribution! thanks huiwq1990!

Pls accept our CLA to start CI progress.

2023-02-03 01:36 UTC, fengxsong requested changes
Key in strings should be the named.FullName()

2023-02-05 07:03 UTC, fanux approved these changes

2023-02-10 05:41 UTC, fanux approved these changes

2023-02-10 07:35 UTC, cuisongliu approved these changes

2023-02-10 10:43 UTC, zzjin commented
@huiwq1990 Once CLA is agreed, we can merge this pr asap.

2023-02-11 03:52 UTC, cuisongliu approved these changes

2023-02-11 04:33 UTC, fengxsong approved these changes

2023-02-11 04:35 UTC, merged