bugfix: change CRI version
labring/sealos pull request #2680
Opened 2023-02-27 10:30 UTC by mond77

2023-02-27 10:34 UTC, mond77 commented
```
root@lmaster:~/install/sealos# sealos run labring/kubernetes:v1.25.6 labring/calico:v3.24.1 --single
```
```
root@lmaster:~/install/sealos# sealos run labring/kubernetes:v1.26.0
```
```
root@lmaster:~/install/sealos/cmd/sealos# kubectl get nodes
NAME      STATUS   ROLES           AGE     VERSION
lmaster   Ready    control-plane   4m45s   v1.26.0
```

2023-02-27 14:10 UTC, cuisongliu commented
add test using sealos-action ci ?

2023-02-27 14:30 UTC, cuisongliu commented
> > add test using sealos-action ci ?
> 
> I cann't understand. And how to use it?

https://github.com/labring/sealos/blob/main/.github/workflows/test_run.yml

add test unit for upgrade ?

2023-02-27 15:49 UTC, cuisongliu requested changes

2023-02-27 15:49 UTC, cuisongliu commented on pkg/runtime/upgrade.go
> +	if err := modifyFile("/etc/image-cri-shim.yaml", "version: v1alpha2", "version: v1"); err != nil {
1. Does this just seem to be a local modification? What if the node executed by sealos is not in the cluster?
2. Image-cri-shim is executed at each node, and the modification should modify all nodes.

2023-03-01 00:46 UTC, mond77 commented on pkg/runtime/upgrade.go
> +	}
done

2023-03-01 01:47 UTC, cuisongliu approved these changes

2023-03-01 01:47 UTC, merged