feat new desktop
labring/sealos pull request #3059
Opened 2023-05-08 11:36 UTC by zjy365

2023-05-09 06:52 UTC, xudaotutou commented on frontend/desktop/src/components/floating_button/index.tsx
有些注释没删

2023-05-09 06:59 UTC, xudaotutou commented on frontend/desktop/src/pages/api/desktop/getInstalledApps.ts
环境变量的注释没删

2023-05-09 07:02 UTC, xudaotutou commented on frontend/desktop/src/types/app.ts
把app_store里的type整合一下

2023-05-09 09:36 UTC, zjy365 commented on frontend/desktop/src/types/app.ts
ok

2023-05-09 10:14 UTC, c121914yu commented on frontend/desktop/src/stores/app.ts
> +            state.runner.loadApps(state.installedApps.map((app) => app.key));
这里应该不用初始化吧？app没还运行

2023-05-09 10:14 UTC, c121914yu commented on frontend/desktop/src/utils/delay.ts
合并到tools文件里？

2023-05-09 10:34 UTC, xudaotutou commented on frontend/desktop/src/stores/app.ts
> +            state.runner.loadApps(state.installedApps.map((app) => app.key));
这里是装载app,用来收集app的key

2023-05-12 04:09 UTC, lingdie requested changes

2023-05-12 04:09 UTC, lingdie commented on frontend/desktop/deploy/Kubefile
> -USER 65532:65532
please merge main codes and fix cluster image build.

2023-05-12 04:09 UTC, lingdie commented on frontend/desktop/deploy/README.md
> -
This one too.

2023-05-12 06:31 UTC, zzjin approved these changes

2023-05-12 06:47 UTC, lingdie approved these changes

2023-05-12 07:04 UTC, merged