Separate database svc and minio svc
labring/sealos pull request #4447
Opened 2023-12-26 06:51 UTC by nowinkeyy

2023-12-26 11:03 UTC, fanux commented
I don’t understand what this PR is used for. You need to add a more detailed explanation.

2023-12-26 11:06 UTC, fanux commented on service/database/server/server.go
> +	listener, err := net.Listen("tcp", c.Server.ListenAddress)
Why not use some http framework, like go-restful

2023-12-27 02:55 UTC, nowinkeyy commented
> I don’t understand what this PR is used for. You need to add a more detailed explanation.

The database and object-storage deploy the same monitoring service respectively, and the service code needs to be split, and the code optimization has not progressed.

2024-01-02 06:23 UTC, lingdie requested changes

2024-01-02 06:23 UTC, lingdie commented on service/database/deploy/manifests/deploy.yaml
> +        memory: 1024Mi
fix this.

2024-01-02 06:37 UTC, lingdie approved these changes

2024-01-02 06:53 UTC, merged