fix object storage monitor
labring/sealos pull request #4691
Opened 2024-04-19 04:06 UTC by bxy4543

2024-04-19 06:08 UTC, zhangguanzhang requested changes

2024-04-19 06:08 UTC, zhangguanzhang commented on controllers/pkg/objectstorage/metric_parser.go
> +	return clnt, nil
为啥不直接
```golang 
return privateNewMetricsClient(endpointURL, jwtToken, secure)
```

2024-04-19 06:08 UTC, zhangguanzhang commented on controllers/pkg/objectstorage/metric_parser.go
> +	return token, nil
这里也是

2024-04-22 03:40 UTC, bxy4543 commented on controllers/pkg/objectstorage/metric_parser.go
> +	return clnt, nil
对的，我写傻了

2024-04-24 07:20 UTC, lingdie approved these changes

2024-04-24 07:23 UTC, merged